name: GPExpansion
version: ${project.version}
main: dev.towki.gpexpansion.GPExpansionPlugin
description: GriefPrevention Expansion
api-version: '1.20'
author: Towki
website: https://discord.com/invite/pCKdCX6nYr
folia-supported: true

dependencies:
  server:
    GriefPrevention:
      load: BEFORE
      required: false
      join-classpath: true
    Vault:
      load: BEFORE
      required: false
      join-classpath: true
    VaultUnlocked:
      load: BEFORE
      required: false
      join-classpath: true
    packetevents:
      load: BEFORE
      required: false
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true
    ItemsAdder:
      load: BEFORE
      required: false
      join-classpath: true
    Oraxen:
      load: BEFORE
      required: false
      join-classpath: true
    Nexo:
      load: BEFORE
      required: false
      join-classpath: true

# Register our listeners
listeners:
  - dev.towki.gpexpansion.listener.SignListener
  - dev.towki.gpexpansion.listener.BanEnforcementListener
  - dev.towki.gpexpansion.listener.CommandInterceptListener

# Register our commands
commands:
  claim:
    description: Claim management command
    usage: /<command>
    permission: griefprevention.claims
  confirm:
    description: Confirm actions
    usage: /<command>
    permission: griefprevention.sign.confirm
  gpx:
    description: GPExpansion admin commands
    usage: /<command>
    permission: griefprevention.admin
  mailbox:
    description: Mailbox setup wizard command
    usage: /<command>
    permission: griefprevention.sign.create.mailbox
  rentclaim:
    description: Rent claim setup wizard command
    usage: /<command>
    permission: griefprevention.sign.create.rent
  sellclaim:
    description: Sell claim setup wizard command
    usage: /<command>
    permission: griefprevention.sign.create.sell
  claiminfo:
    description: Show detailed claim information
    usage: /<command> [claimId]
    permission: griefprevention.claiminfo

permissions:
  griefprevention.claims:
    description: Allows access to /claim
    default: true

  griefprevention.claim.name:
    description: Allows using /claim name
    default: true

  griefprevention.claim.name.anywhere:
    description: Allows using /claim name outside own claims
    default: true
  
  griefprevention.claim.name.other:
    description: Allows using /claim name on other claims
    default: op

  griefprevention.claim.name.color.*:
    description: Allows specific colors via & codes and MiniMessage tags
    default: op

  griefprevention.claim.name.format.*:
    description: Allows specific formats via & codes and MiniMessage tags
    default: op

  griefprevention.claim.name.color.gradient:
    description: Allows gradient/rainbow MiniMessage tags
    default: op

  # === CLAIM DESCRIPTION PERMISSIONS ===
  griefprevention.claim.description:
    description: Allows using /claim desc
    default: true

  griefprevention.claim.description.anywhere:
    description: Allows using /claim desc outside own claims
    default: true

  griefprevention.claim.description.other:
    description: Allows using /claim desc on other claims
    default: op

  griefprevention.claim.icon:
    description: Allows using /claim icon
    default: true

  griefprevention.claim.icon.other:
    description: Allows using /claim icon on other claims
    default: op

  # === CLAIM BAN PERMISSIONS ===
  griefprevention.claim.ban:
    description: Allows using /claim ban
    default: true

  griefprevention.claim.ban.anywhere:
    description: Allows using /claim ban outside own claims
    default: true

  griefprevention.claim.ban.other:
    description: Allows using /claim ban on other claims
    default: op

  griefprevention.claim.unban:
    description: Allows using /claim unban
    default: true

  griefprevention.claim.unban.anywhere:
    description: Allows using /claim unban outside own claims
    default: true

  griefprevention.claim.unban.other:
    description: Allows using /claim unban on other claims
    default: op

  griefprevention.claim.banlist:
    description: Allows using /claim banlist
    default: true

  griefprevention.claim.banlist.anywhere:
    description: Allows using /claim banlist outside own claims
    default: true

  griefprevention.claim.banlist.other:
    description: Allows using /claim banlist on other claims
    default: op

  # === RENT SIGN PERMISSIONS ===
  griefprevention.sign.create.rent:
    description: Allows creating rent signs
    default: true

  griefprevention.sign.use.rent:
    description: Allows using rent signs
    default: true

  griefprevention.sign.create.rent.anywhere:
    description: Allows creating rent signs outside own claims
    default: op

  griefprevention.sign.rent.money:
    description: Allows using money economy for rent signs
    default: true

  griefprevention.sign.rent.exp:
    description: Allows using exp economy for rent signs
    default: op

  griefprevention.sign.rent.claimblocks:
    description: Allows using claimblocks economy for rent signs
    default: op

  griefprevention.sign.rent.item:
    description: Allows using item economy for rent signs
    default: op

  # === SELL/BUY SIGN PERMISSIONS ===
  griefprevention.sign.create.sell:
    description: Allows creating sell/buy signs
    default: true

  griefprevention.sign.use.sell:
    description: Allows using sell/buy signs
    default: true

  griefprevention.sign.create.sell.anywhere:
    description: Allows creating sell signs outside own claims
    default: op

  griefprevention.sign.sell.money:
    description: Allows using money economy for sell signs
    default: true

  griefprevention.sign.sell.exp:
    description: Allows using exp economy for sell signs
    default: op

  griefprevention.sign.sell.claimblocks:
    description: Allows using claimblocks economy for sell signs
    default: op

  griefprevention.sign.sell.item:
    description: Allows using item economy for sell signs
    default: op

  griefprevention.sign.create.buy:
    description: Allows creating buy signs (alias for sell)
    default: true

  griefprevention.sign.use.buy:
    description: Allows using buy signs (alias for sell)
    default: true

  griefprevention.sign.create.buy.1:
    description: Allows creating 1 buy sign
    default: false

  griefprevention.sign.create.buy.5:
    description: Allows creating 5 buy signs
    default: false

  griefprevention.sign.create.buy.10:
    description: Allows creating 10 buy signs
    default: false

  griefprevention.sign.create.buy.25:
    description: Allows creating 25 buy signs
    default: false

  griefprevention.sign.create.buy.50:
    description: Allows creating 50 buy signs
    default: false

  griefprevention.sign.create.buy.100:
    description: Allows creating 100 buy signs
    default: false

  griefprevention.sign.create.rent.1:
    description: Allows creating 1 rent sign
    default: false

  griefprevention.sign.create.rent.5:
    description: Allows creating 5 rent signs
    default: false

  griefprevention.sign.create.rent.10:
    description: Allows creating 10 rent signs
    default: false

  griefprevention.sign.create.rent.25:
    description: Allows creating 25 rent signs
    default: false

  griefprevention.sign.create.rent.50:
    description: Allows creating 50 rent signs
    default: false

  griefprevention.sign.create.rent.100:
    description: Allows creating 100 rent signs
    default: false

  # === MAILBOX SIGN PERMISSIONS ===
  griefprevention.sign.create.mailbox:
    description: Allows creating mailbox signs
    default: true

  griefprevention.sign.use.mailbox:
    description: Allows using mailbox signs
    default: true

  griefprevention.sign.mailbox.money:
    description: Allows using money economy for mailbox signs
    default: true

  griefprevention.sign.mailbox.exp:
    description: Allows using exp economy for mailbox signs
    default: op

  griefprevention.sign.mailbox.claimblocks:
    description: Allows using claimblocks economy for mailbox signs
    default: op

  griefprevention.sign.mailbox.item:
    description: Allows using item economy for mailbox signs
    default: op

  griefprevention.sign.create.mailbox.1:
    description: Allows creating 1 mailbox sign
    default: false

  griefprevention.sign.create.mailbox.5:
    description: Allows creating 5 mailbox signs
    default: false

  griefprevention.sign.create.mailbox.10:
    description: Allows creating 10 mailbox signs
    default: false

  griefprevention.sign.create.mailbox.25:
    description: Allows creating 25 mailbox signs
    default: false

  griefprevention.sign.create.mailbox.50:
    description: Allows creating 50 mailbox signs
    default: false

  griefprevention.sign.create.mailbox.100:
    description: Allows creating 100 mailbox signs
    default: false

  # === SELF MAILBOX PERMISSIONS ===
  griefprevention.sign.create.self-mailbox:
    description: Allows creating instant self mailboxes (wall sign on container)
    default: true

  griefprevention.sign.create.self-mailbox.1:
    description: Allows creating 1 self mailbox per claim
    default: false

  griefprevention.sign.create.self-mailbox.2:
    description: Allows creating 2 self mailboxes per claim
    default: false

  griefprevention.sign.create.self-mailbox.5:
    description: Allows creating 5 self mailboxes per claim
    default: false

  griefprevention.sign.create.self-mailbox.10:
    description: Allows creating 10 self mailboxes per claim
    default: false

  griefprevention.sign.admin:
    description: Allows admin sign management
    default: op

  griefprevention.admin:
    description: Allows access to GPExpansion admin commands
    default: op

  gpx.admin:
    description: Allows viewing migration notices
    default: op

  griefprevention.adminclaimslist:
    description: Allows viewing admin claims list
    default: op

  griefprevention.transferclaim:
    description: Allows using /claim transfer
    default: op

  # Claim info permissions
  griefprevention.claiminfo:
    description: Allows using /claiminfo command
    default: true

  griefprevention.claiminfo.other:
    description: Allows viewing info for claims you don't own
    default: op

  # Claim ban/unban permissions
  griefprevention.claim.ban:
    description: Allows banning players from your claims
    default: true

  griefprevention.claim.ban.other:
    description: Allows banning players from claims you don't own
    default: op

  griefprevention.claim.unban:
    description: Allows unbanning players from your claims
    default: true

  griefprevention.claim.unban.other:
    description: Allows unbanning players from claims you don't own
    default: op

  # === CLAIM TELEPORT PERMISSIONS ===
  griefprevention.claim.teleport:
    description: Allows teleporting to claims
    default: true

  griefprevention.claim.teleport.other:
    description: Allows teleporting other players to claims
    default: op

  griefprevention.claim.setspawn:
    description: Allows setting teleport spawn point for your claims
    default: true

  griefprevention.claim.setspawn.other:
    description: Allows setting spawn points for other players' claims
    default: op

  griefprevention.claim.gui.setclaimflag.own:
    description: Allows opening claim flags GUI for own claims
    default: true

  griefprevention.claim.gui.setclaimflag.anywhere:
    description: Allows opening claim flags GUI for other claims
    default: op

  gpflags.command.setclaimflag:
    description: Allows using GPFlags claim flag commands
    default: op

  gpflags.flag.*:
    description: Allows toggling any GPFlags flag
    default: op

  griefprevention.claim.gui.globallist:
    description: Allows viewing the global public claim list GUI
    default: true

  griefprevention.claim.gui.return:
    description: Allows using /claim ! to return to last viewed GUI
    default: op

  griefprevention.claim.toggleglobal:
    description: Allows toggling public listing for your own claims
    default: true

  griefprevention.claim.toggleglobal.other:
    description: Allows toggling public listing for claims you don't own
    default: op

  griefprevention.evict:
    description: Allows evicting claim renters
    default: op

  griefprevention.evict.other:
    description: Allows evicting renters from other claims
    default: op

  griefprevention.eviction.bypass:
    description: Allows bypassing eviction protections
    default: op

  # === GLOBAL CLAIM LIMIT PERMISSIONS ===
  griefprevention.claim.toggleglobal.*:
    description: Allows unlimited global claims
    default: op

  griefprevention.claim.toggleglobal.5:
    description: Allows up to 5 global claims (default)
    default: true

  griefprevention.claim.toggleglobal.10:
    description: Allows up to 10 global claims
    default: false

  griefprevention.claim.toggleglobal.25:
    description: Allows up to 25 global claims
    default: false

  griefprevention.claim.toggleglobal.50:
    description: Allows up to 50 global claims
    default: false

  griefprevention.claim.toggleglobal.100:
    description: Allows up to 100 global claims
    default: false

  # === CLAIM COLOR/FORMAT PERMISSIONS (for /claim name and /claim desc) ===
  griefprevention.claim.color.*:
    description: Allows using all color codes in claim names and descriptions
    default: op

  griefprevention.claim.color.black:
    description: Allows using &0 (black) in claim names/descriptions
    default: true

  griefprevention.claim.color.dark_blue:
    description: Allows using &1 (dark blue) in claim names/descriptions
    default: true

  griefprevention.claim.color.dark_green:
    description: Allows using &2 (dark green) in claim names/descriptions
    default: true

  griefprevention.claim.color.dark_aqua:
    description: Allows using &3 (dark aqua) in claim names/descriptions
    default: true

  griefprevention.claim.color.dark_red:
    description: Allows using &4 (dark red) in claim names/descriptions
    default: true

  griefprevention.claim.color.dark_purple:
    description: Allows using &5 (dark purple) in claim names/descriptions
    default: true

  griefprevention.claim.color.gold:
    description: Allows using &6 (gold) in claim names/descriptions
    default: true

  griefprevention.claim.color.gray:
    description: Allows using &7 (gray) in claim names/descriptions
    default: true

  griefprevention.claim.color.dark_gray:
    description: Allows using &8 (dark gray) in claim names/descriptions
    default: true

  griefprevention.claim.color.blue:
    description: Allows using &9 (blue) in claim names/descriptions
    default: true

  griefprevention.claim.color.green:
    description: Allows using &a (green) in claim names/descriptions
    default: true

  griefprevention.claim.color.aqua:
    description: Allows using &b (aqua) in claim names/descriptions
    default: true

  griefprevention.claim.color.red:
    description: Allows using &c (red) in claim names/descriptions
    default: true

  griefprevention.claim.color.light_purple:
    description: Allows using &d (light purple) in claim names/descriptions
    default: true

  griefprevention.claim.color.yellow:
    description: Allows using &e (yellow) in claim names/descriptions
    default: true

  griefprevention.claim.color.white:
    description: Allows using &f (white) in claim names/descriptions
    default: true

  griefprevention.claim.format.*:
    description: Allows using all formatting codes in claim names and descriptions
    default: op

  griefprevention.claim.format.bold:
    description: Allows using &l (bold) in claim names/descriptions
    default: true

  griefprevention.claim.format.italic:
    description: Allows using &o (italic) in claim names/descriptions
    default: true

  griefprevention.claim.format.underline:
    description: Allows using &n (underline) in claim names/descriptions
    default: false

  griefprevention.claim.format.strikethrough:
    description: Allows using &m (strikethrough) in claim names/descriptions
    default: false

  griefprevention.claim.format.obfuscated:
    description: Allows using &k (obfuscated/magic) in claim names/descriptions
    default: false

  griefprevention.claim.format.reset:
    description: Allows using &r (reset) in claim names/descriptions
    default: true
